### ISSUE TITLE
Issue with suppress_nst on 0.14.1 & 0.14.2

### ISSUE THREAD

**Issue by jarjee** [tazz4843/whisper-rs#209]
I'm not entirely sure if this is a bindgen issue or not, but pulling this library from cargo, I'm unable to build it:
```bash
error[E0609]: no field `suppress_nst` on type `whisper_full_params`
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/whisper-rs-0.14.2/src/whisper_params.rs:308:17
    |
308 |         self.fp.suppress_nst = suppress_nst;
    |                 ^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `strategy`, `n_threads`, `n_max_text_ctx`, `offset_ms`, `duration_ms` ... and 48 others
```

For `target/debug/build/whisper-rs-sys-443ad82263b2bf2c/out/bindings.rs`:
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_full_params {
    // ....
    pub suppress_non_speech_tokens: bool,
```

This looks to have been introduced in #199, but when building this library locally I don't seem to be able to replicate the issue, so I'm guessing there's something wrong between `whisper-rs` and `whisper-rs-sys`?

**Comment by tazz4843** [comment]
https://docs.rs/crate/whisper-rs/latest/source/src/whisper_params.rs#308

Seems like somehow that still got pushed. I have no clue how that happened or how it continued to build despite that. I'll go ahead and push 0.14.3.

**Comment by tazz4843** [comment]
Actually looking at the code closer I believe you might be using `whisper-rs-sys` 0.12.0 instead of 0.12.1 as 0.12.0 was yanked because it failed to update properly. Have you ran a `cargo update` yet?

**Comment by tazz4843** [comment]
https://docs.rs/crate/whisper-rs-sys/0.12.0/source/whisper.cpp/src/whisper.cpp#4747 0.12.0 has `suppress_non_speech_tokens`

https://docs.rs/crate/whisper-rs-sys/0.12.1/source/whisper.cpp/src/whisper.cpp#4680 0.12.1 has `suppress_nst`

**Comment by jarjee** [comment]
Strangely enough, I have done a cargo update - I'll see if it replicates with a new repo and check if it's not something I've done.

**Comment by IvanProg00** [comment]
I encountered a similar issue. Everything worked smoothly locally, but when I tried to build a docker image with `whisper-rs = 0.14.2`, I encountered the following error.:

```
error[E0609]: no field `suppress_nst` on type `whisper_full_params`
   --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/whisper-rs-0.14.2/src/whisper_params.rs:308:17
    |
308 |         self.fp.suppress_nst = suppress_nst;
    |                 ^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `strategy`, `n_threads`, `n_max_text_ctx`, `offset_ms`, `duration_ms` ... and 48 others
```

**Comment by tazz4843** [comment]
https://docs.rs/crate/whisper-rs-sys/0.12.1/source/src/bindings.rs#4539

It actually looks like your systems are failing to generate bindings. I'll push a `0.12.2` of `-sys` with the proper generated `bindings.rs`

**Comment by jarjee** [comment]
Following up, in my case I was using `hipblas`, and I needed the `AMDGPU_TARGETS` environment flag to be set to correctly generate the bindings, otherwise it'd fall back on the default bindings.rs.
